### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by GenericProgrammer1234** [GenericProgrammer1234/Pyratch#17]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jfami/Desktop/Pyratch/interface.py", line 99, in user
    user, info = user_load(username)
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/jfami/Desktop/Pyratch/interface.py", line 43, in user_load
    comment_count = len(user.comments())
                        ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scratchattach/_user.py", line 542, in comments
    return self._get_comments(URL)[:limit]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
I have gone to three user pages and have encountered this error.

**Comment by zaid1442011** [comment]
It works fine with me.
127.0.0.1 - - [27/Aug/2023 16:58:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2023 16:58:31] "GET /static/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [27/Aug/2023 16:58:37] "GET /users/__Falcon-Games__ HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2023 16:58:37] "GET /static/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [27/Aug/2023 16:58:54] "GET /users/zaid1442011 HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2023 16:58:54] "GET /static/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [27/Aug/2023 16:59:27] "GET /users/mybearworld HTTP/1.1" 200 -
127.0.0.1 - - [27/Aug/2023 16:59:28] "GET /static/styles.css HTTP/1.1" 304 -

**Comment by GenericProgrammer1234** [comment]
Which version of Pyratch are you using?

**Comment by GenericProgrammer1234** [comment]
Also it works for them user pages and it doesn't work for other user pages.

**Comment by zaid1442011** [comment]
> Also it works for them user pages and it doesn't work for other user pages.

I will see.

**Comment by zaid1442011** [comment]
> Also it works for them user pages and it doesn't work for other user pages.

Which pages did you visit.

**Comment by GenericProgrammer1234** [comment]
> Which pages did you visit.

Redstone1080 and PPPDUD's profile, at least that's the ones I remember.

**Comment by zaid1442011** [comment]
* Serving Flask app 'interface'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 419-385-535
127.0.0.1 - - [28/Aug/2023 11:47:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2023 11:47:32] "GET /static/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Aug/2023 11:47:43] "GET /users/Redstone1080 HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2023 11:47:43] "GET /static/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Aug/2023 11:47:47] "GET /users/PPPDUD HTTP/1.1" 200 -
127.0.0.1 - - [28/Aug/2023 11:47:47] "GET /static/styles.css HTTP/1.1" 304 -

**Comment by GenericProgrammer1234** [comment]
Okay I am going to run Pyratch again, maybe there was something before that is fixed now.

**Comment by zaid1442011** [comment]
Does it work?

**Comment by zaid1442011** [comment]
I am going to close it for now.
